apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: camel-k
spec:
  channel: alpha
  config:
    resources: {}
  installPlanApproval: Automatic
  name: camel-k
  source: community-operators
  sourceNamespace: openshift-marketplace